[package]
name = "rltk-tutorial"
version = "0.1.0"
edition = "2018"
authors = ["Kevin Garner <kevin@kgar.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.0" }
specs = "0.16.1"
specs-derive = "0.4.1"
